### PR TITLE
Included a DateTimeFormatter formatter and LocalDate date

### PR DESCRIPTION
**Pull request by kjiaxuan**
Added a LocalDate variable in Date.java
so dates are now not in string format unless use toString()

i think can use this to sort dates, or implement set feature (budget for a certain period of time etc)

### CODE REVIEW

**Comment by kjiaxuan** [comment]
#91

**Comment by geezlouisee** [comment]
Good job adding in the Date API! I think this will be useful when we want to implement most of our features. I also read somewhere that the API will help to ensure our time implementation to be immutable and hence, also thread-safe.

**Review by JeremyLoye — COMMENTED** [review]
It is a good idea to implement a LocalDate object for our dates. Do consider some revisions in implementation though:
The isValidDate method currently has repeat checks namely the check of test string with VALIDATION_REGEX and the LocalDate parse check. Possible to remove the regex with current implementation.

**Review by eugeneyl — COMMENTED** [review]
Adding the DateTimeFormatter will help in preventing the input of strings that are not actually date and prevent confusion during the implementation.

**Pull request merged**
